### ISSUE TITLE
bug: toggle disable not working as expected

### ISSUE THREAD

**Issue by agustinusnathaniel** [kodingdotninja/use-toggle#2]
### Reproduce link:
https://react-ts-c7hgfd.stackblitz.io
https://stackblitz.com/edit/react-ts-c7hgfd?file=ToggleTest.tsx

### cause: 
currently the disable callback in `use-toggle` hook are setting the state to `true`.

### possible fix:
set disable callback in `use-toggle` to set state to `false`
https://github.com/kodingdotninja/use-toggle/blob/main/src/use-toggle.ts#L31

**Comment by grikomsn** [comment]
My bad, was half awake when I worked on this. 😂

Fixed in 4512fc700b3b3d7aac208469604d7b176615624d.
